# Generated by Django 3.2.7 on 2021-12-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20211223_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
