# Generated by Django 3.2.7 on 2021-12-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_alter_profile_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
