# Generated by Django 3.2.7 on 2021-12-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_tracker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='income_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
