# Generated by Django 3.2.7 on 2021-12-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_auto_20211227_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('income_category', models.CharField(blank=True, max_length=100, null=True)),
                ('expenses', models.FloatField(default=0)),
            ],
        ),
    ]
