# Generated by Django 3.2.7 on 2021-12-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0015_add_excel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_excel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracker.profile'),
        ),
    ]
