# Generated by Django 3.2.7 on 2022-01-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0018_profile_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curr_value',
            field=models.FloatField(default=84.21),
            preserve_default=False,
        ),
    ]
